[probe] Repeat the examples in the codec build

diff --git a/.github/workflows/basic.yml b/.github/workflows/basic.yml
--- a/.github/workflows/basic.yml
+++ b/.github/workflows/basic.yml
@@ -28,7 +28,7 @@ name: build
 
 on:
   push:
-    branches: [ master, develop ]
+    branches: [ master, develop, 'tf_probe_*' ]
     paths-ignore:
       - '**/*.md'
   pull_request:
@@ -54,14 +54,7 @@ jobs:
         os: [ubuntu-22.04]
         # All supported types
         # type: [basic, basic-no-hdfs, basic-codec, hdfs, gcs, azure, azurite, aws]
-        type: [basic, basic-no-hdfs, basic-codec, hdfs, gcs, azure, aws]
-        include:
-          - os: macos-15-intel
-            type: basic
-            openssl-version: 1.1
-          - os: macos-15-intel
-            type: basic
-            openssl-version: 3
+        type: [basic-codec]
 
     runs-on: ${{ matrix.os }}
 
@@ -180,7 +173,13 @@ jobs:
       working-directory:  ${{env.CMAKE_BUILD_DIR}}
       run: |
         make -j4
-        make tests -j 4
+        make tests -j 4 || echo "first make tests failed"
+        fails=0
+        for i in $(seq 15); do
+          if ! make ci_tests > ci_tests_$i.log 2>&1; then fails=$((fails+1)); tail -4 ci_tests_$i.log; fi
+        done
+        echo "PROBE: ci_tests failed $fails of 15"
+        exit 0
         export TILEDB_BENCHMARK=1
         time TILEDB_BOOKKEEPING_STATS=1 TILEDB_CACHE=1 test/test_sparse_array_benchmark
         export TILEDB_DISABLE_FILE_LOCKING=1
